"""improve_master_service_many_to_many

Revision ID: d9d2b4771eb6
Revises: dcac512eba62
Create Date: 2025-11-21 20:04:41.055280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d2b4771eb6'
down_revision: Union[str, None] = 'dcac512eba62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Проверяем и создаем индексы только если их еще нет
    from sqlalchemy import inspect
    
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # Получаем список существующих индексов
    try:
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('master_service_association')]
    except Exception:
        existing_indexes = []
    
    # Создаем индексы для быстрого поиска (только если их еще нет)
    if 'ix_master_service_master' not in existing_indexes:
        try:
    op.create_index('ix_master_service_master', 'master_service_association', ['master_id'], unique=False)
        except Exception:
            pass  # Индекс уже существует
    
    if 'ix_master_service_service' not in existing_indexes:
        try:
    op.create_index('ix_master_service_service', 'master_service_association', ['service_id'], unique=False)
        except Exception:
            pass  # Индекс уже существует
    
    # Для SQLite foreign keys с CASCADE уже должны быть настроены на уровне таблицы
    # SQLite не поддерживает изменение foreign keys без пересоздания таблицы
    # Поэтому просто проверяем, что индексы созданы
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_master_service_service', 'master_service_association', type_='foreignkey')
    op.drop_constraint('fk_master_service_master', 'master_service_association', type_='foreignkey')
    op.create_foreign_key(
        'master_service_association_service_id_fkey',
        'master_service_association',
        'services',
        ['service_id'],
        ['id']
    )
    op.create_foreign_key(
        'master_service_association_master_id_fkey',
        'master_service_association',
        'masters',
        ['master_id'],
        ['id']
    )
    op.drop_index('ix_master_service_service', table_name='master_service_association')
    op.drop_index('ix_master_service_master', table_name='master_service_association')
    # ### end Alembic commands ###
